In [3]:
import numpy as np

### Process Model

In [11]:
# give an example here first
v_sb_b = np.array([2, 2, 0])
w_sb_b = np.array([0, 0, 3])
bp = np.array([2, 1, 0])

In [12]:
v_bpc_b = np.zeros((3, ))
v_bpc_b

array([0., 0., 0.])

$$
v_{bp_c}^b=-v_{sb}^b+-w_{sb}^b\times b_p = -\begin{bmatrix}
 \mathbf{I} & \left [ \mathbf{p_c} \right ] 
\end{bmatrix}\begin{bmatrix}
v_{sb}^b \\ w_{sb}^b
\end{bmatrix}
$$

Direct cross product

In [13]:
v_bpc_b = -v_sb_b + -np.cross(w_sb_b, bp)
print(-v_sb_b, -np.cross(w_sb_b, bp), v_bpc_b)

[-2 -2  0] [ 3 -6  0] [ 1 -8  0]


skew-symmetric matrix 

In [14]:
def skew(vector):
    """
    this function returns a numpy array with the skew symmetric cross product matrix for vector.
    the skew symmetric cross product matrix is defined such that
    np.cross(a, b) = np.dot(skew(a), b)

    :param vector: An array like vector to create the skew symmetric cross product matrix for
    :return: A numpy array of the skew symmetric cross product vector
    """

    return np.array([[0, -vector[2], vector[1]], 
                     [vector[2], 0, -vector[0]], 
                     [-vector[1], vector[0], 0]])
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
I = np.identity(3)
pc_ = -skew(bp) # should be negative
B = -np.append(I, pc_, axis=1)
xi = np.append(v_sb_b, w_sb_b, axis=0)
xi.transpose(),xi, B

(array([2, 2, 0, 0, 0, 3]),
 array([2, 2, 0, 0, 0, 3]),
 array([[-1., -0., -0., -0., -0.,  1.],
        [-0., -1., -0., -0., -0., -2.],
        [-0., -0., -1., -1.,  2., -0.]]))

In [19]:
B @ xi

array([ 1., -8.,  0.])

WHYYYYYYYYY!!!!

$$
    \mathbf{a} \times \mathbf{b} = - \left ( \mathbf{b} \times \mathbf{a} \right ) 
$$

State transition function

In [22]:
def f_contact(x, lv, av, dt):
    input = np.append(lv, av, axis=0)
    B = -dt*np.append(np.identity(3), -skew(x), axis=1)
    A = np.identity(3)
    prior_predict = A @ x + B @ input 
    return prior_predict

In [23]:
f_contact(np.array([1, 1, 0]), lv=v_sb_b, av=w_sb_b, dt=1)

array([ 2., -4.,  0.])